CREATE TABLE LeadCustomer 
(
	CustomerID INTEGER UNIQUE PRIMARY KEY,
	FirstName VARCHAR(20)  NOT NULL,
	Surname VARCHAR(40)  NOT NULL,
	BillingAddress VARCHAR(200)  NOT NULL,
	email  VARCHAR(30) NOT NULL
)

CREATE TABLE Passenger 
(
	PassengerID INTEGER UNIQUE PRIMARY KEY,
	FirstName VARCHAR(20)  NOT NULL,
	Surname VARCHAR(40)  NOT NULL,
	PassportNo VARCHAR(30) NOT NULL,
	Nationality VARCHAR(30) NOT NULL,
	Dob DATE NOT NULL
)

CREATE TABLE Flight 
(
	FlightID INTEGER UNIQUE PRIMARY KEY,
	FlightDate TIMESTAMP NOT NULL, 
	Origin VARCHAR(30) NOT NULL,
	Destination VARCHAR(30) NOT NULL,
	MaxCapacity INTEGER NOT NULL,
	PricePerSeat DECIMAL NOT NULL

)
CREATE TABLE FlightBooking 
(
	BookingID INTEGER UNIQUE PRIMARY KEY,
	CustomerID INTEGER NOT NULL,
	FlightID INTEGER NOT NULL, 
	NumSeats INTEGER NOT NULL,
	Status CHAR(1) NOT NULL,
	BookingTime TIMESTAMP NOT NULL,
	TotalCost DECIMAL
	
)
CREATE TABLE SeatBooking
(
	BookingID INTEGER UNIQUE PRIMARY KEY,
	PassengerID INTEGER NOT NULL,
	SeatNumber CHAR(4) NOT NULL
	
)
